// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZb-bngMBFFbRqOrtrBhC1xMdUOR2C1Ss',
    appId: '1:593164910252:web:52eae1e399930209b22909',
    messagingSenderId: '593164910252',
    projectId: 'amplopku',
    authDomain: 'amplopku.firebaseapp.com',
    storageBucket: 'amplopku.firebasestorage.app',
    measurementId: 'G-XS3KGMQG86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA543q2e0FmA7P7C0COvCs9BD0TUBKtj-E',
    appId: '1:593164910252:android:531ed8e16e55daeab22909',
    messagingSenderId: '593164910252',
    projectId: 'amplopku',
    storageBucket: 'amplopku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP47GEJ-2-jAcLtJtr1dutR806fAa4SNI',
    appId: '1:593164910252:ios:8283f7a0b5993180b22909',
    messagingSenderId: '593164910252',
    projectId: 'amplopku',
    storageBucket: 'amplopku.firebasestorage.app',
    iosBundleId: 'com.example.amplopku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP47GEJ-2-jAcLtJtr1dutR806fAa4SNI',
    appId: '1:593164910252:ios:8283f7a0b5993180b22909',
    messagingSenderId: '593164910252',
    projectId: 'amplopku',
    storageBucket: 'amplopku.firebasestorage.app',
    iosBundleId: 'com.example.amplopku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZb-bngMBFFbRqOrtrBhC1xMdUOR2C1Ss',
    appId: '1:593164910252:web:a7baa836c739ad67b22909',
    messagingSenderId: '593164910252',
    projectId: 'amplopku',
    authDomain: 'amplopku.firebaseapp.com',
    storageBucket: 'amplopku.firebasestorage.app',
    measurementId: 'G-1QGZJX25KL',
  );
}
